### PR TITLE
Fix tutorials to work with Qiskit 1.0

### PR DESCRIPTION
**Pull request by woodsp-ibm**
### Summary

Qiskit 1,0 removed the deprecated `qiskit.tools` which included some `.jupyter` from which the magics that did the version and copyright were imported. This PR adds a local file in the tutorials folder that contains just these magics and changes the import to use this.

Update: more needed fixing after this - see comments below.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
Seems the notebook that shows VQE with Aer with a noise etc fails now that the magics are fixed

```
      1 from qiskit_aer.noise import NoiseModel
----> 2 from qiskit.providers.fake_provider import FakeVigo
      4 # fake providers contain data from real IBM Quantum devices stored in Qiskit,
      5 # and are useful for extracting realistic noise models.
      6 device = FakeVigo()

ImportError: cannot import name 'FakeVigo' from 'qiskit.providers.fake_provider' (/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/qiskit/providers/fake_provider/__init__.py)
```

Will fix/update this

**Comment by woodsp-ibm** [comment]
I see I need to update the Grover notebook too as this fails since tools is gone

```
from qiskit.tools.visualization import plot_histogram
````

**Comment by woodsp-ibm** [comment]
I downloaded the `tutorials3.12` and was surprised to see the histogram was not there in the output of 07 grover one - it had worked for me locally under 3.9. But its there in `turorials3.8`, and we publish docs under 3.8 so I guess its ok. I'll check after this (hopefully) final change to fix styles (just had warnings about iqx saying it was not found) and if its not there I'll raise an issue so perhaps it can be investigated in the future.

**Comment by woodsp-ibm** [comment]
This is good to go now.

**Review by ElePT — APPROVED** [review]
Thanks Steve! LGTM, I just re-ran all the tutorials to make sure that the version tables show the latest versions and that the plotted circuits now follow the new color scheme. No more qiskit-terra and qiskit versions reported at the same time!

Screenshot 2024-02-19 at 11 30 39
